# Generated by hand for ExerciseUserPoints
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('exercise', '0051_revealrule_show_zero_points_immediately'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseUserPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_count', models.PositiveIntegerField(default=0)),
                ('all_count', models.PositiveIntegerField(default=0)),
                ('official_best_grade', models.IntegerField(default=0)),
                ('official_last_grade', models.IntegerField(default=0)),
                ('all_best_grade', models.IntegerField(default=0)),
                ('all_last_grade', models.IntegerField(default=0)),
                ('forced_points', models.IntegerField(blank=True, null=True)),
                ('last_submission_id', models.IntegerField(blank=True, null=True)),
                ('best_submission_id', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to='exercise.baseexercise', verbose_name='LABEL_EXERCISE')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_points', to='userprofile.userprofile', verbose_name='LABEL_SUBMITTER')),
            ],
            options={
                'app_label': 'exercise',
                'unique_together': {('exercise', 'submitter')},
            },
        ),
        migrations.AddIndex(
            model_name='exerciseuserpoints',
            index=models.Index(fields=['exercise', 'submitter'], name='exercise_su_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseuserpoints',
            index=models.Index(fields=['submitter'], name='exercise_su_submit_idx'),
        ),
        migrations.AddIndex(
            model_name='exerciseuserpoints',
            index=models.Index(fields=['exercise'], name='exercise_su_ex_idx'),
        ),
    ]
