name: Deploy A+ Documentation

on:
  push:
    branches:
      - sphinxdocs  # or the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # specify your Python version

      - name: Install dependencies
        run: |
          sudo apt install build-dep python3-lxml
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme

      - name: Build documentation
        run: |
          sphinx-build -b html docs/source docs/build/_build/html

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone --depth 1 --branch gh-pages https://github.com/sayravai/apluslms.github.io.git gh-pages
          rsync -av --delete docs/_build/html/ gh-pages/docs/aplus/
          cd gh-pages
          git add .
          git commit -m "Update A+ Sphinx documentation"
          git push origin gh-pages